### ISSUE TITLE
Syntax highlighting not working on home page

### ISSUE THREAD

**Issue by budiariyanto** [digitalcraftsman/hugo-icarus-theme#10] opened 2015-12-06 17:27 UTC
When i run the site with this theme and see the homepage, syntax highlighting is not working, but when i open the post with permalink, it looks great.

**Comment by digitalcraftsman** [comment] 2015-12-08 19:33
Hello @budiariyanto,

with homepage your refer to the [index page](http://themes.gohugo.io/theme/hugo-icarus/), right? The summary of a post shown there doesn't render code examples. That is right and implemented by design into Hugo. You can read more about this in a [forum thread](https://discuss.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396).

I've added the `markdownify` template function to render the summary. In combination with `<!--more-->` it should work (atleast with the demo content that I've used for testing). Everything you put before this comment will be part of the summary. 

Post an update if it doesn't work as expected.

**Comment by budiariyanto** [comment] 2015-12-09 14:08
Great! After I add the `<!--more-->` it works totally fine. Thanks for the help.

**Closed as completed** 2015-12-12 18:15 UTC
